# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-pallet" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/pallet"]
    end
  end

  version "1.0.11"

  on_macos do
    sha256 "fe1a0f514545212b25bd6a62f212c34909a3bb746f771276446d3d8ff901db39"
    url "https://github.com/KEINOS/go-pallet/releases/download/v#{version}/go-pallet_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "6ab9ca08e5ce04fa31afcef0f1ceaf62b220e2735f96dfb60a529e7c34adb620"
      url "https://github.com/KEINOS/go-pallet/releases/download/v#{version}/go-pallet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "196592aa0047865a08c73c11c2c92467ce8a28f3b16e94bd0413320b64b6eaba"
      url "https://github.com/KEINOS/go-pallet/releases/download/v#{version}/go-pallet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "go-pallet"
  desc "Color pallet extractor from an image."
  homepage "https://github.com/KEINOS/go-pallet/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pallet"

  # No zap stanza required
end
