# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-pallet" do
  version "1.0.9"

  on_macos do
    sha256 "cd8b7686b241d0795812b489e15263fdaa3f3ec1a55005bbbabf2f5ad1fddbe6"
    url "https://github.com/KEINOS/go-pallet/releases/download/v#{version}/go-pallet_#{version}_darwin_all.tar.gz",
        verified: "github.com/KEINOS/go-pallet"
  end

  on_linux do
    on_intel do
      sha256 "bc955f25374cfb70a204712270de1af31ac7cdd4728c576534ff2586afe104c8"
      url "https://github.com/KEINOS/go-pallet/releases/download/v#{version}/go-pallet_#{version}_linux_amd64.tar.gz",
        verified: "github.com/KEINOS/go-pallet"
    end
    on_arm do
      sha256 "9a8d5c9e3ceb95bc35237398dcf604ae7d7a5835ed6d6701f42ac5d6eb6dded3"
      url "https://github.com/KEINOS/go-pallet/releases/download/v#{version}/go-pallet_#{version}_linux_arm64.tar.gz",
        verified: "github.com/KEINOS/go-pallet"
    end
  end

  name "go-pallet"
  desc "Color pallet extractor from an image."
  homepage "https://github.com/KEINOS/go-pallet/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pallet"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pallet"]
    end
  end

  # No zap stanza required

end
