# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-pallet" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/pallet"]
    end
  end

  version "1.0.10"

  on_macos do
    sha256 "e0fc6449eeb9f699cf21fa31aff487b992fdf8eb65d94cb5e01b3606f80f39eb"
    url "https://github.com/KEINOS/go-pallet/releases/download/v#{version}/go-pallet_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "8a976fff044e5fe4b2a4c1eefce29ae0889ff5355ae410dcd77db2928d3bd4b9"
      url "https://github.com/KEINOS/go-pallet/releases/download/v#{version}/go-pallet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bdc5cec39f2123be0a8dede49ebc8408dc8ad9f6e6b48968ea5b16762e2c6a60"
      url "https://github.com/KEINOS/go-pallet/releases/download/v#{version}/go-pallet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "go-pallet"
  desc "Color pallet extractor from an image."
  homepage "https://github.com/KEINOS/go-pallet/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pallet"

  # No zap stanza required
end
