# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevGoSample < Formula
  desc "This is a sample app of github.com/KEINOS/dev-go. It simply prints 'Hello, Gopher!'."
  homepage "https://github.com/KEINOS/dev-go/"
  version "1.4.0"

  on_macos do
    url "https://github.com/KEINOS/dev-go/releases/download/v1.4.0/dev-go_1.4.0_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "88983420fbdc321a820e4de8b8accecb2634f872a6498707c32226b768e8d650"

    def install
      bin.install "dev-go-sample"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KEINOS/dev-go/releases/download/v1.4.0/dev-go_1.4.0_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "cfa7684ac337354dc8118c646376013dc489c88f0bc03792647baaee566b2478"

      def install
        bin.install "dev-go-sample"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/dev-go/releases/download/v1.4.0/dev-go_1.4.0_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "2206e67021fcdf9dba4b24852b48d5d25d07e90326a9060204b1372bec2f4808"

      def install
        bin.install "dev-go-sample"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/dev-go/releases/download/v1.4.0/dev-go_1.4.0_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "79b2778852c91dc35b0ec44ed3fc59e9dd8390172bf99975843df50be36a2245"

      def install
        bin.install "dev-go-sample"
      end
    end
  end

  test do
    system "#{bin}/dev-go-sample --version"
  end
end
