# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genrawid < Formula
  desc "generate a unique consistent number from the imput as a rawid of SQLite3."
  homepage "https://github.com/KEINOS/go-genrawid/"
  version "0.0.1-alpha"

  on_macos do
    url "https://github.com/KEINOS/dev-go/releases/download/v0.0.1-alpha/go-genrawid_0.0.1-alpha_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "b03066f02a079a33075cf275a7b5c2fe77598e637742cb1a2efc3d2140c7cdb3"

    def install
      bin.install "genrawid"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/dev-go/releases/download/v0.0.1-alpha/go-genrawid_0.0.1-alpha_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b27a4cbea50482ea4e381a6f86a100d40671035025c70e6bd4ea7340093cc7ef"

      def install
        bin.install "genrawid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KEINOS/dev-go/releases/download/v0.0.1-alpha/go-genrawid_0.0.1-alpha_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "90fd4a9150deb1fb5e0845580b6ba9b28b4d01489c3832e1205e3f9422f19aaf"

      def install
        bin.install "genrawid"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/dev-go/releases/download/v0.0.1-alpha/go-genrawid_0.0.1-alpha_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "7ae9fe4cfbb2318dcd718776679f4dfd901eace9c35a0433f210a2a0b191a7a1"

      def install
        bin.install "genrawid"
      end
    end
  end

  test do
    system "#{bin}/genrawid --version"
  end
end
