# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genrawid < Formula
  desc "generate a unique consistent number from the imput as a rawid of SQLite3."
  homepage "https://github.com/KEINOS/go-genrawid/"
  version "0.1.0"

  on_macos do
    url "https://github.com/KEINOS/go-genrawid/releases/download/v0.1.0/go-genrawid_0.1.0_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "0c78d1900bef7b44a2db0a7c922f3318cc25dc8843d7b9540c1e4365ebfc512d"

    def install
      bin.install "genrawid"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/go-genrawid/releases/download/v0.1.0/go-genrawid_0.1.0_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "6781fe475397dda731567d0357159b541b01dd9fe4ccb11ddd6ce6f4d74b099d"

      def install
        bin.install "genrawid"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/go-genrawid/releases/download/v0.1.0/go-genrawid_0.1.0_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "4e0bcdcac0aa27af18704564e9fa0b6c2fe3708035900d78ff77f471dfa88946"

      def install
        bin.install "genrawid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KEINOS/go-genrawid/releases/download/v0.1.0/go-genrawid_0.1.0_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "3448b33b4e9cbeda9a1cebcdae26ddcf2edf3170869b3d58447bcbc9883795ac"

      def install
        bin.install "genrawid"
      end
    end
  end

  test do
    system "#{bin}/genrawid --version"
  end
end
