# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoPallet < Formula
  desc "Color pallet extractor from an image."
  homepage "https://github.com/KEINOS/go-pallet/"
  version "1.0.0-beta3"

  on_macos do
    url "https://github.com/KEINOS/go-pallet/releases/download/v1.0.0-beta3/go-pallet_1.0.0-beta3_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "63d6eb18f63c3949f5691062dd588521c89308f3d43eb9fa7872f3b7318043ba"

    def install
      bin.install "pallet"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KEINOS/go-pallet/releases/download/v1.0.0-beta3/go-pallet_1.0.0-beta3_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "1a78b7f2a4165371d7adc36bcd87b13ac114a4abd8c2e932ba0a26059d1b9462"

      def install
        bin.install "pallet"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/go-pallet/releases/download/v1.0.0-beta3/go-pallet_1.0.0-beta3_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "c863d0fe167652812dc68755128aaab12cf9fda622c80be61ad501bf4dccda51"

      def install
        bin.install "pallet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/go-pallet/releases/download/v1.0.0-beta3/go-pallet_1.0.0-beta3_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "807d98616ac7915930f3940dfd14d8888f82a858006fd2c47fe83cc38274f406"

      def install
        bin.install "pallet"
      end
    end
  end

  test do
    system "#{bin}/pallet --version"
  end
end
