# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoPallet < Formula
  desc "Color pallet extractor from an image."
  homepage "https://github.com/KEINOS/go-pallet/"
  version "1.0.0-beta2"

  on_macos do
    url "https://github.com/KEINOS/go-pallet/releases/download/v1.0.0-beta2/go-pallet_1.0.0-beta2_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "34dd6444d455a8f82fcc7453d9b907f3edcd731998aa69da0de84cf0442c843d"

    def install
      bin.install "pallet"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/go-pallet/releases/download/v1.0.0-beta2/go-pallet_1.0.0-beta2_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "9330c5e5f1aa0d8db636f660faf1f21d3fe6b93e41e94f936264f97879c04628"

      def install
        bin.install "pallet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KEINOS/go-pallet/releases/download/v1.0.0-beta2/go-pallet_1.0.0-beta2_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b6efa832100472f2a9fcedd93d0ff482f76ac21fed8e59aed13ac4ab8f0a2243"

      def install
        bin.install "pallet"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/go-pallet/releases/download/v1.0.0-beta2/go-pallet_1.0.0-beta2_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "5ced652b381ff987c1cb8a1aa65108fd7c1afa37455c5ac62a7eb0ce581410ed"

      def install
        bin.install "pallet"
      end
    end
  end

  test do
    system "#{bin}/pallet --version"
  end
end
