# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostars < Formula
  desc "Prints the attraction gravity of a Go Package."
  homepage "https://github.com/KEINOS/gostars/"
  version "0.0.2"

  on_macos do
    url "https://github.com/KEINOS/gostars/releases/download/v0.0.2/gostars_0.0.2_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "f513e0f0bc492492906b24b2fac0167ffa127667ed03e9a04527472202f8674a"

    def install
      bin.install "gostars"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/gostars/releases/download/v0.0.2/gostars_0.0.2_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "0042b80c3a477574b331feec297c0f91de6381cfbcd818240e5c6f0ffaff82a8"

      def install
        bin.install "gostars"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/gostars/releases/download/v0.0.2/gostars_0.0.2_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "644306cd9b031b72d91832f07815fea23e2f1b204daadb60714b40db0538eb31"

      def install
        bin.install "gostars"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KEINOS/gostars/releases/download/v0.0.2/gostars_0.0.2_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "ceb2ed6ad599f380ec97124c95db291b41d97a95490e9437ac7e0d02e2fe9b9a"

      def install
        bin.install "gostars"
      end
    end
  end

  test do
    system "#{bin}/gostars -h
    "
  end
end
