# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostars < Formula
  desc "Prints the attraction gravity of a Go Package."
  homepage "https://github.com/KEINOS/gostars/"
  version "0.0.3"

  on_macos do
    url "https://github.com/KEINOS/gostars/releases/download/v0.0.3/gostars_0.0.3_darwin_all.zip", using: CurlDownloadStrategy
    sha256 "78f97907f7acc6a71dbaba54609e48dc6d17a8edcd5517d55ab3d3f5540de58d"

    define_method(:install) do
      bin.install "gostars"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/gostars/releases/download/v0.0.3/gostars_0.0.3_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ae3db29ccd943ce8907ea809d2f66bc8f145374a2f0b7efe6406ec0a3f7e3ed2"
      define_method(:install) do
        bin.install "gostars"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/gostars/releases/download/v0.0.3/gostars_0.0.3_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "52bca821117da3048a9d97123088fb398f0a7ac27c1232fc33379ca2b1278f0c"
      define_method(:install) do
        bin.install "gostars"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/gostars/releases/download/v0.0.3/gostars_0.0.3_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ed8172a6d31eab9bc6ea910d25f161bdd6803627b60654462fc0f0685b0c06de"
      define_method(:install) do
        bin.install "gostars"
      end
    end
  end

  test do
    system "#{bin}/gostars -h"
  end
end
