# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostars < Formula
  desc "Prints the attraction gravity of a Go Package."
  homepage "https://github.com/KEINOS/gostars/"
  version "0.0.1"

  on_macos do
    url "https://github.com/KEINOS/gostars/releases/download/v0.0.1/gostars_0.0.1_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "c1b28ee0f0564a3142254da8fcf8cadda40168d661bf49c9c82122eb65e82d3e"

    def install
      bin.install "gostars"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/gostars/releases/download/v0.0.1/gostars_0.0.1_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "7f5a98a07c039f8aaeaa6f23c5967864bf67d79aeb8456f8b96ebe89f3c6802c"

      def install
        bin.install "gostars"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KEINOS/gostars/releases/download/v0.0.1/gostars_0.0.1_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "207d4a62946c3544cedb8a1d1610b51d585bdda8bff81b0124401658ea44d5fc"

      def install
        bin.install "gostars"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/gostars/releases/download/v0.0.1/gostars_0.0.1_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "8da1c12aa5b2993ab648ffad996c361155c3858aefc46117cf4e2591fc0ab873"

      def install
        bin.install "gostars"
      end
    end
  end

  test do
    system "#{bin}/gostars -h
    "
  end
end
