# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whereami < Formula
  desc "This is a command line utility that prints the current global/public IP address."
  homepage "https://github.com/KEINOS/whereami/"
  version "1.0.0-alpha"

  on_macos do
    url "https://github.com/KEINOS/whereami/releases/download/v1.0.0-alpha/whereami_1.0.0-alpha_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "cdaed5ccf3bb1bccf3ac6d2a690aedfc9ab86d91fa9c532291804d8fc2877bd7"

    def install
      bin.install "whereami"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/whereami/releases/download/v1.0.0-alpha/whereami_1.0.0-alpha_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "5523c9f46f1f3e45c61b3bf5b5640811f303dca48ed65f39c9994e76cdae29a6"

      def install
        bin.install "whereami"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/whereami/releases/download/v1.0.0-alpha/whereami_1.0.0-alpha_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "94fbac31a55630ecff963e0f03fda930b12873bad90c93e52c75802316558542"

      def install
        bin.install "whereami"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KEINOS/whereami/releases/download/v1.0.0-alpha/whereami_1.0.0-alpha_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e0fad7bc38b7ec19dad32501934327430dec09645a75459cb5b240e14c54f828"

      def install
        bin.install "whereami"
      end
    end
  end

  test do
    system "#{bin}/whereami --version"
  end
end
