# This workflow runs the `brew` download functionality via Docker container.
name: "genrawid"

on:
  workflow_dispatch:
  push:
  schedule:
    # Runs at 16:40 UTC on day-of-month 2 (Every day-of-month 2 at AM 01:40 JST, my time)
    # See: https://crontab.guru/
    - cron: '40 16 2 * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Run tests on Linux via container
        if: runner.os == 'Linux'
        run: docker compose run genrawid

      - name: Run tests on macOS
        if: runner.os == 'macOS'
        run: |
          : # Install shellspec
          brew update
          brew install shellspec/shellspec/shellspec
          shellspec -v
          : # Run test
          cd Tests && \
          shellspec ./spec/genrawid_spec.sh
